title: Haumohio
description: The wind of information
exclude: [README.md]
include: [".well-known"]

# applies pretty for all
permalink: pretty

defaults:
    - scope:
        path: ""
        type: posts
      values:
        permalink: /blog/:title

plugins:
  - jekyll-relative-links

collections:
  - contents
